/*
 * AccountPage.java
 *
 * Created on February 27, 2011, 12:48 PM
 */

package com.rameses.enterprise.treasury.master;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  jzamss
 */
@StyleSheet
@Template(FormPage.class)
public class ItemAcctPage extends javax.swing.JPanel {
    
    /** Creates new form AccountPage */
    public ItemAcctPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();

        setPreferredSize(new java.awt.Dimension(542, 498));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Account Details");
        formPanel1.setBorder(xTitledBorder1);
        formPanel1.setCaptionWidth(95);
        xLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel1.setCaption("State");
        xLabel1.setDepends(new String[] {"selectedItem"});
        xLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        xLabel1.setName("entity.state");
        xLabel1.setPreferredSize(new java.awt.Dimension(150, 18));
        formPanel1.add(xLabel1);

        xTextField2.setCaption("Title");
        xTextField2.setDepends(new String[] {"selectedItem"});
        xTextField2.setName("entity.accttitle");
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField2.setRequired(true);
        formPanel1.add(xTextField2);

        xComboBox1.setCaption("Fund");
        xComboBox1.setExpression("#{fundname}");
        xComboBox1.setImmediate(true);
        xComboBox1.setItems("fundList");
        xComboBox1.setName("fund");
        xComboBox1.setPreferredSize(new java.awt.Dimension(200, 22));
        xComboBox1.setRequired(true);
        formPanel1.add(xComboBox1);

        xComboBox2.setCaption("System Type");
        xComboBox2.setDepends(new String[] {"selectedItem"});
        xComboBox2.setImmediate(true);
        xComboBox2.setItems("systemTypeList");
        xComboBox2.setName("entity.systype");
        xComboBox2.setPreferredSize(new java.awt.Dimension(200, 22));
        formPanel1.add(xComboBox2);

        xComboBox4.setCaption("Grouping");
        xComboBox4.setExpression("#{name}");
        xComboBox4.setImmediate(true);
        xComboBox4.setItems("itemAccountGroupList");
        xComboBox4.setName("itemacctgroup");
        xComboBox4.setPreferredSize(new java.awt.Dimension(200, 22));
        formPanel1.add(xComboBox4);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Optional Settings");
        formPanel2.setBorder(xTitledBorder2);
        xComboBox3.setCaption("Amount Type");
        xComboBox3.setCaptionWidth(100);
        xComboBox3.setDepends(new String[] {"selectedItem"});
        xComboBox3.setImmediate(true);
        xComboBox3.setItems("valueTypeList");
        xComboBox3.setName("entity.valuetype");
        xComboBox3.setPreferredSize(new java.awt.Dimension(120, 22));
        formPanel2.add(xComboBox3);

        xNumberField1.setCaption("Default Value");
        xNumberField1.setCaptionWidth(100);
        xNumberField1.setDepends(new String[] {"selectedItem", "entity.amounttype"});
        xNumberField1.setName("entity.defaultvalue");
        xNumberField1.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel2.add(xNumberField1);

        xTextField3.setCaption("Rule Code");
        xTextField3.setCaptionWidth(100);
        xTextField3.setDepends(new String[] {"selectedItem"});
        xTextField3.setName("entity.code");
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xTextField3);

        xCheckBox1.setCaption(" Allow Discount?");
        xCheckBox1.setCaptionWidth(100);
        xCheckBox1.setCheckValue(1);
        xCheckBox1.setDepends(new String[] {"selectedItem"});
        xCheckBox1.setName("entity.allowdiscount");
        xCheckBox1.setUncheckValue(0);
        formPanel2.add(xCheckBox1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    // End of variables declaration//GEN-END:variables
    
}
