/*
 * AFReceiptPage.java
 *
 * Created on August 10, 2013, 4:33 AM
 */

package com.rameses.gov.treasury.ris;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  Elmo
 */
@Template(FormPage.class)
@StyleSheet
public class AFIssuePage extends javax.swing.JPanel {
    
    /** Creates new form AFReceiptPage */
    public AFIssuePage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel4 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        xButton1 = new com.rameses.rcp.control.XButton();
        jLabel1 = new javax.swing.JLabel();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xDataTable2 = new com.rameses.rcp.control.XDataTable();
        jLabel2 = new javax.swing.JLabel();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Request Info");
        jPanel4.setBorder(xTitledBorder1);

        xFormPanel1.setCaptionWidth(120);
        xLabel4.setCaption("Date Filed");
        xLabel4.setExpression("#{ris.dtfiled}");
        xLabel4.setName("entity.txntype");
        xFormPanel1.add(xLabel4);

        xLabel2.setCaption("Requester");
        xLabel2.setExpression("#{ris.requester.name}");
        xLabel2.setName("entity.txntype");
        xFormPanel1.add(xLabel2);

        xLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel3.setExpression("#{entity.issueno}");
        xLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));

        xFormPanel2.setCaptionWidth(120);
        xLabel6.setCaption("RIS No");
        xLabel6.setExpression("#{ris.risno}");
        xLabel6.setName("entity.txntype");
        xFormPanel2.add(xLabel6);

        xLabel7.setCaption("Txn Type");
        xLabel7.setExpression("#{ris.txntype}");
        xLabel7.setName("entity.txntype");
        xFormPanel2.add(xLabel7);

        jLabel3.setText("Issue  No:");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(xFormPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(xFormPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 266, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 72, Short.MAX_VALUE)
                .add(jLabel3)
                .add(21, 21, 21)
                .add(xLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(32, 32, 32))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(xFormPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(xFormPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel3)
                    .add(xLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Request for Accountable Forms ");
        jPanel1.setBorder(xTitledBorder2);
        xDataTable1.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column("item.code", "Stock", 100, 100, 100, false, true, true, false, null, new com.rameses.rcp.common.TextColumnHandler()),
            new com.rameses.rcp.common.Column("item.description", "Description", 100, 0, 0, false, true, true, false, null, new com.rameses.rcp.common.TextColumnHandler()),
            new com.rameses.rcp.common.Column("unit", "Unit", 50, 50, 50, false, true, true, false, null, new com.rameses.rcp.common.TextColumnHandler()),
            new com.rameses.rcp.common.Column("qty", "Qty Requested", 100, 100, 100, false, true, true, false, null, new com.rameses.rcp.common.IntegerColumnHandler(null, -1, -1)),
            new com.rameses.rcp.common.Column("qtyissued", "Qty To Issue", 100, 100, 100, false, true, true, true, null, new com.rameses.rcp.common.IntegerColumnHandler(null, -1, -1)),
            new com.rameses.rcp.common.Column("remarks", "Remarks", 100, 0, 0, false, true, true, false, null, new com.rameses.rcp.common.TextColumnHandler())
        });
        xDataTable1.setHandler("reqItemModel");
        xDataTable1.setId("requestItems");
        xDataTable1.setName("selectedItem");
        jPanel1.add(xDataTable1);
        xDataTable1.setBounds(10, 46, 798, 124);

        xButton1.setName("loadStock");
        xButton1.setText("Load Available Stock");
        jPanel1.add(xButton1);
        xButton1.setBounds(10, 174, 134, 23);

        jLabel1.setText("Edit the qty to issue and click the \"load available stock\" to process. Click on save and post to complete the transfer ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 26, 726, 14);

        xCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox1.setCaption("Show All");
        xCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox1.setName("showSelected");
        xCheckBox1.setOpaque(false);
        xCheckBox1.setText("Show only items selected from above");
        jPanel1.add(xCheckBox1);
        xCheckBox1.setBounds(598, 202, 200, 15);

        xDataTable2.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column("af", "Stock", 100, 0, 0, false, true, true, false, null, new com.rameses.rcp.common.TextColumnHandler()),
            new com.rameses.rcp.common.Column("qty", "Qty ", 100, 0, 0, false, true, true, false, null, new com.rameses.rcp.common.TextColumnHandler()).set("alignment","CENTER"),
            new com.rameses.rcp.common.Column("startstub", "Start Stub", 100, 0, 0, false, true, true, false, null, new com.rameses.rcp.common.TextColumnHandler()).set("alignment","CENTER"),
            new com.rameses.rcp.common.Column("endstub", "End Stub", 100, 0, 0, false, true, true, false, null, new com.rameses.rcp.common.TextColumnHandler()).set("alignment","CENTER"),
            new com.rameses.rcp.common.Column("startseries", "Start Series", 100, 0, 0, false, true, true, false, null, new com.rameses.rcp.common.TextColumnHandler()).set("alignment","CENTER"),
            new com.rameses.rcp.common.Column("endseries", "End Series", 100, 0, 0, false, true, true, false, null, new com.rameses.rcp.common.TextColumnHandler()).set("alignment","CENTER"),
            new com.rameses.rcp.common.Column("prefix", "Prefix", 100, 0, 0, false, true, true, false, null, new com.rameses.rcp.common.TextColumnHandler()).set("alignment","CENTER"),
            new com.rameses.rcp.common.Column("suffix", "Suffix", 100, 0, 0, false, true, true, false, null, new com.rameses.rcp.common.TextColumnHandler()).set("alignment","CENTER")
        });
        xDataTable2.setDepends(new String[] {"selectedItem", "showSelected"});
        xDataTable2.setDynamic(true);
        xDataTable2.setHandler("issuedItemModel");
        jPanel1.add(xDataTable2);
        xDataTable2.setBounds(14, 226, 788, 168);

        jLabel2.setText("Available in stock");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(16, 206, 168, 14);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 413, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XDataTable xDataTable2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    // End of variables declaration//GEN-END:variables
    
}
