/*
 * UserPage.java
 *
 * Created on August 1, 2013, 7:52 AM
 */

package com.rameses.admin.user;

import com.rameses.osiris2.themes.OKCancelPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  Elmo
 */
@Template(OKCancelPage.class)
public class ResetPasswordPage extends javax.swing.JPanel {
    
    /** Creates new form UserPage */
    public ResetPasswordPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xPasswordField1 = new com.rameses.rcp.control.XPasswordField();
        xPasswordField2 = new com.rameses.rcp.control.XPasswordField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setPadding(new java.awt.Insets(30, 15, 15, 15));
        xTitledBorder1.setTitle("General Information");
        xFormPanel1.setBorder(xTitledBorder1);
        xFormPanel1.setCaptionWidth(120);
        xPasswordField1.setText("xPasswordField1");
        xPasswordField1.setCaption("New Password");
        xPasswordField1.setName("pwd.newpwd");
        xPasswordField1.setPreferredSize(new java.awt.Dimension(0, 22));
        xPasswordField1.setRequired(true);
        xFormPanel1.add(xPasswordField1);

        xPasswordField2.setText("xPasswordField1");
        xPasswordField2.setCaption("Confirm Password");
        xPasswordField2.setName("pwd.confirmpwd");
        xPasswordField2.setPreferredSize(new java.awt.Dimension(0, 22));
        xPasswordField2.setRequired(true);
        xFormPanel1.add(xPasswordField2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(xFormPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(xFormPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XPasswordField xPasswordField1;
    private com.rameses.rcp.control.XPasswordField xPasswordField2;
    // End of variables declaration//GEN-END:variables
    
}
