/*
 * AFInventoryQuery.java
 *
 * Created on July 23, 2013, 11:18 AM
 */

package com.rameses.gov.treasury.afcontrol;

import com.rameses.osiris2.themes.OKCancelPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  Elmo
 */
@Template(OKCancelPage.class)
public class AFControlChangeMode extends javax.swing.JPanel {
    
    /** Creates new form AFInventoryQuery */
    public AFControlChangeMode() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xRadio1 = new com.rameses.rcp.control.XRadio();
        xRadio2 = new com.rameses.rcp.control.XRadio();
        xRadio3 = new com.rameses.rcp.control.XRadio();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(298, 193));
        setRequestFocusEnabled(false);

        xFormPanel1.setCaptionWidth(120);
        xFormPanel1.setCellspacing(0);
        xFormPanel1.setPadding(new java.awt.Insets(0, 5, 5, 5));
        xRadio1.setName("entity.mode");
        xRadio1.setOptionValue("ONLINE");
        xRadio1.setPreferredSize(new java.awt.Dimension(0, 23));
        xRadio1.setShowCaption(false);
        xRadio1.setText("Online");
        xFormPanel1.add(xRadio1);

        xRadio2.setName("entity.mode");
        xRadio2.setOptionValue("OFFLINE");
        xRadio2.setPreferredSize(new java.awt.Dimension(0, 23));
        xRadio2.setShowCaption(false);
        xRadio2.setText("Offline");
        xFormPanel1.add(xRadio2);

        xRadio3.setName("entity.mode");
        xRadio3.setOptionValue("CAPTURE");
        xRadio3.setPreferredSize(new java.awt.Dimension(0, 23));
        xRadio3.setShowCaption(false);
        xRadio3.setText("Capture");
        xFormPanel1.add(xRadio3);

        jLabel1.setText("Select  mode of collection");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(xFormPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jLabel1)
                .add(24, 24, 24)
                .add(xFormPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XRadio xRadio1;
    private com.rameses.rcp.control.XRadio xRadio2;
    private com.rameses.rcp.control.XRadio xRadio3;
    // End of variables declaration//GEN-END:variables
    
}
